DROP TABLE IF EXISTS usuario;
DROP TABLE IF EXISTS empleado;
DROP TABLE IF EXISTS cliente;
DROP TABLE IF EXISTS dlistapre;
DROP TABLE IF EXISTS producto;
DROP TABLE IF EXISTS umedida;
DROP TABLE IF EXISTS factor;
DROP TABLE IF EXISTS cpedido;
DROP TABLE IF EXISTS dpedido;
DROP TABLE IF EXISTS parametro;
DROP TABLE IF EXISTS canal;
DROP TABLE IF EXISTS cliente_movil_nuevo;
DROP TABLE IF EXISTS direccion;
DROP TABLE IF EXISTS politica;
DROP TABLE IF EXISTS tipoproducto;
DROP TABLE IF EXISTS bodega;
DROP TABLE IF EXISTS emisor;
DROP TABLE IF EXISTS tipopago;
DROP TABLE IF EXISTS documento;
DROP TABLE IF EXISTS banco;
DROP TABLE IF EXISTS crecibo;
DROP TABLE IF EXISTS drecibo;
DROP TABLE IF EXISTS dcancelacion;
DROP TABLE IF EXISTS ddocumento;
DROP TABLE IF EXISTS cfactura;
DROP TABLE IF EXISTS dfactura;
DROP TABLE IF EXISTS impresora;
DROP TABLE IF EXISTS novedad;
DROP TABLE IF EXISTS cli_ruta;
DROP TABLE IF EXISTS zona;
DROP TABLE IF EXISTS clienteinfo;
DROP TABLE IF EXISTS cingreso;
DROP TABLE IF EXISTS dingreso;
DROP TABLE IF EXISTS saldoinv;
DROP TABLE IF EXISTS manual;
DROP TABLE IF EXISTS dpedidoinfo;
DROP TABLE IF EXISTS imagen_producto;
DROP TABLE IF EXISTS preventa;
DROP TABLE IF EXISTS marca;
DROP TABLE IF EXISTS clasificacion1;
DROP TABLE IF EXISTS modelo;
DROP TABLE IF EXISTS producto_modelo;
DROP TABLE IF EXISTS producto_tmp;
CREATE TABLE IF NOT EXISTS modelo(id INTEGER, nombre TEXT, img BLOB, imagen TEXT, extension TEXT);
CREATE TABLE IF NOT EXISTS producto_tmp(id INTEGER, cantidad DOUBLE, total DOUBLE, precio DOUBLE, preventa TEXT);
CREATE TABLE IF NOT EXISTS producto_modelo(id INTEGER, producto INTEGER, modelo INTEGER, fechaact TEXT, tipo INTEGER);
CREATE TABLE IF NOT EXISTS marca(id INTEGER, NOMBRE TEXT);
CREATE TABLE IF NOT EXISTS clasificacion1(id INTEGER, NOMBRE TEXT);
CREATE TABLE IF NOT EXISTS usuario(id INTEGER PRIMARY KEY);
CREATE TABLE IF NOT EXISTS empleado(usuario INTEGER, idEmpleado INTEGER, idEmpresa INTEGER, nombreEmpresa TEXT);
CREATE TABLE IF NOT EXISTS cliente(id INTEGER PRIMARY KEY, identificacion TEXT, nombre TEXT, pol INTEGER, listapre INTEGER, descuento DOUBLE, diasplazo INTEGER, calleprincipal TEXT, callesecundaria TEXT, numeracion TEXT, telefono TEXT, email TEXT, activo INTEGER);
CREATE TABLE IF NOT EXISTS dlistapre(id INTEGER, producto INTEGER, precio DOUBLE, iddlp INTEGER, fechaact TEXT, tipo INTEGEr);
CREATE TABLE IF NOT EXISTS producto(id INTEGER PRIMARY KEY, nombre TEXT, umedida INTEGER, stock DOUBLE, promocion DOUBLE, idTipo INTEGER, impuesto INTEGER, urlimg TEXT, myImage BLOB, codigo TEXT, nuevo INTEGER, fechaact TEXT, tipo INTEGER, marca INTEGER, clasificacion1 INTEGER, fichatecnica TEXT, promo INTEGER, promoDescripcion TEXT, empaque TEXT, llegado INTEGER);
CREATE TABLE IF NOT EXISTS umedida(id INTEGER, nombre TEXT);
CREATE TABLE IF NOT EXISTS banco(_id INTEGER, _nombre TEXT);
CREATE TABLE IF NOT EXISTS factor(umedida INTEGER, producto INTEGER, factor DOUBLE, id INTEGER, fechaact TEXT, tipo INTEGER);
CREATE TABLE IF NOT EXISTS cpedido(id INTEGER PRIMARY KEY AUTOINCREMENT, cliente INTEGER , descuento DOUBLE, diasplazo INTEGER, fecha DATE, estado INTEGER, sincronizado INTEGER, total DOUBLE, observaciones TEXT, direccion INTEGER, politica INTEGER, coordx DOUBLE, coordy DOUBLE, idNovedad INTEGER, optimo INTEGER, subEmpId INTEGER, obsequio TEXT, subtotal DOUBLE, iva DOUBLE, idzona INTEGER);
CREATE TABLE IF NOT EXISTS dpedido(id INTEGER PRIMARY KEY AUTOINCREMENT, cpedido INTEGER, producto INTEGER, cantidad DOUBLE, promocion DOUBLE, descuento DOUBLE, precio DOUBLE, umedida INTEGER, total DOUBLE, bodega INTEGER, cordcom INTEGER, preventa INTEGER, observaciones TEXT,descuento2 DOUBLE, descuento3 DOUBLE);
CREATE TABLE IF NOT EXISTS parametro(id INTEGER PRIMARY KEY AUTOINCREMENT, nombre TEXT, valor TEXT);
CREATE TABLE IF NOT EXISTS canal(id INTEGER PRIMARY KEY, nombre TEXT);
CREATE TABLE IF NOT EXISTS cliente_movil_nuevo(id INTEGER PRIMARY KEY, cedula TEXT, apellidos TEXT, nombres TEXT, direccion TEXT, telefono TEXT, mail TEXT, canal INTEGER, politica INTEGER, fecNac TEXT, idZona INTEGER, nomComercial TEXT);
CREATE TABLE IF NOT EXISTS direccion(id INTEGER PRIMARY KEY, idcliente INTEGER, calleprincipal TEXT);
CREATE TABLE IF NOT EXISTS politica(id INTEGER PRIMARY KEY, nombre TEXT);
CREATE TABLE IF NOT EXISTS tipoproducto(id INTEGER PRIMARY KEY, nombre TEXT);
CREATE TABLE IF NOT EXISTS bodega(id INTEGER PRIMARY KEY, codigo INTEGER, nombre TEXT, promocion INTEGER);
CREATE TABLE IF NOT EXISTS emisor(id INTEGER, nombre TEXT);
CREATE TABLE IF NOT EXISTS tipopago(id INTEGER, nombre TEXT, contabiliza INTEGER, pidedetalle INTEGER, transaccion INTEGER, retfuente INTEGER, tiporet INTEGER);
CREATE TABLE IF NOT EXISTS ddocumento(id INTEGER, transacc INTEGER, numpago INTEGER,monto DOUBLE, fechaven TEXT,  idcli INTEGER, cancelado DOUBLE, saldo DOUBLE, fechaemi TEXT, doctran TEXT, canceladoruta DOUBLE, idMovil INTEGER);
CREATE TABLE IF NOT EXISTS cfactura(id INTEGER PRIMARY KEY AUTOINCREMENT, cliente INTEGER , descuento DOUBLE, diasplazo INTEGER, fecha DATE, estado INTEGER, sincronizado INTEGER, total DOUBLE, observaciones TEXT, direccion INTEGER, politica INTEGER, coordx DOUBLE, coordy DOUBLE);
CREATE TABLE IF NOT EXISTS dfactura(id INTEGER PRIMARY KEY AUTOINCREMENT, cfactura INTEGER, producto INTEGER, cantidad DOUBLE, promocion DOUBLE, descuento DOUBLE, precio DOUBLE, umedida INTEGER, total DOUBLE, bodega INTEGER);
CREATE TABLE IF NOT EXISTS impresora(id INTEGER PRIMARY KEY AUTOINCREMENT, nombre TEXT, mac TEXT, estado TEXT);
CREATE TABLE IF NOT EXISTS novedad(id INTEGER PRIMARY KEY, codigo TEXT, nombre TEXT, requerido INTEGER );
CREATE TABLE IF NOT EXISTS cli_ruta(id INTEGER PRIMARY KEY, idCli INTEGER, zona INTEGER, direccionCliente INTEGER, cliSemana INTEGER, cliDia INTEGER, cliOrden INTEGER, cliTipo INTEGER, cliOptimo INTEGER, cliEsDia INTEGER);
CREATE TABLE IF NOT EXISTS zona(id INTEGER PRIMARY KEY, nombre TEXT, codigo TEXT, orden INTEGER);
CREATE TABLE IF NOT EXISTS clienteinfo(id INTEGER PRIMARY KEY, idcli INTEGER, calleprincipal TEXT, callesecundaria TEXT, numeracion TEXT, telefono TEXT, email TEXT, idemp INTEGER);
CREATE TABLE IF NOT EXISTS cingreso(id INTEGER PRIMARY KEY, fecha TEXT, empId INTEGER, subEmpId INTEGER, estado INTEGER, transaccion INTEGER, obs TEXT);
CREATE TABLE IF NOT EXISTS dingreso(id INTEGER PRIMARY KEY, cingresoId INTEGER, productoId INTEGER, cantidad DOUBLE, saldo DOUBLE, debcre INTEGER, saldoAux DOUBLE);
CREATE TABLE IF NOT EXISTS saldoinv(id INTEGER PRIMARY KEY , periodo INTEGER, producto INTEGER, empleado INTEGER, subempleado INTEGER, saldoInicial DOUBLE  , salDeb1 DOUBLE  ,  salCre1 DOUBLE  , salDeb2 DOUBLE  , salCre2 DOUBLE  , salDeb3 DOUBLE  , salCre3 DOUBLE  , salDeb4 DOUBLE  , salCre4 DOUBLE  , salDeb5 DOUBLE  , salCre5 DOUBLE  , salDeb6 DOUBLE  , salCre6 DOUBLE  , salDeb7 DOUBLE  , salCre7 DOUBLE  , salDeb8 DOUBLE  , salCre8 DOUBLE  , salDeb9 DOUBLE  , salCre9 DOUBLE  , salDeb10 DOUBLE  , salCre10 DOUBLE  ,salDeb11 DOUBLE  , salCre11 DOUBLE  , salDeb12 DOUBLE  , salCre12 DOUBLE  );
CREATE TABLE IF NOT EXISTS manual(_estado INTEGER);
CREATE TABLE IF NOT EXISTS crecibo(id INTEGER PRIMARY KEY AUTOINCREMENT, fecha TEXT, concepto TEXT,  cliente INTEGER , empleado INTEGER, total DOUBLE, coordx DOUBLE, coordy DOUBLE,estado INTEGER, sincronizado INTEGER, marcado INTEGER);
CREATE TABLE IF NOT EXISTS drecibo(id INTEGER PRIMARY KEY AUTOINCREMENT, crecibo INTEGER, tipopago INTEGER, valor DOUBLE, emisor TEXT, beneficiario TEXT, cliente INTEGER, nrocheque INTEGER, nrocuenta INTEGER, banco INTEGER, debcre INTEGER, nrodocumento TEXT, concepto TEXT, fecha DATE, retautorizacion TEXT, fechacaducidad DATE, retnumcomproba TEXT, fechafactura DATE, retnumfactura TEXT );
CREATE TABLE IF NOT EXISTS dcancelacion(id INTEGER PRIMARY KEY AUTOINCREMENT, documento INTEGER, recibo INTEGER, valor DOUBLE, debcre INTEGER);
CREATE TABLE IF NOT EXISTS dpedidoinfo(id INTEGER, idPedido INTEGER, cliente INTEGER, fecha TEXT, producto TEXT, precio DOUBLE, cantidad DOUBLE, subtotal DOUBLE, iva DOUBLE, total DOUBLE);
CREATE TABLE IF NOT EXISTS imagen_producto(id INTEGER, producto INTEGER, tipo INTEGER, imagen TEXT, extension TEXT, orden INTEGER, fechaact TEXT, img BLOB);
CREATE TABLE IF NOT EXISTS cordcom(id INTEGER, fecha_aprobacion TEXT, fecha_disponibilidad TEXT, numero INTEGER);
CREATE TABLE IF NOT EXISTS dordcom(id INTEGER, cordcom INTEGER, producto INTEGER, bodega INTEGER, unidad INTEGER, cantidad DOUBLE);
CREATE TABLE IF NOT EXISTS preventa(id INTEGER, producto INTEGER, cantidad DOUBLE, fechaDispon TEXT, numOrden INTEGEr, precioPreventa DOUBLE,corid INTEGER);
INSERT INTO parametro(nombre, valor) VALUES('servidor','1.1.1.1');
INSERT INTO parametro(nombre, valor) VALUES('puerto','0');
INSERT INTO parametro(nombre, valor) VALUES('items','10000');
INSERT INTO parametro(nombre, valor) VALUES('iva','12');
INSERT INTO parametro(nombre, valor) VALUES('itemrepetido','FALSE');
INSERT INTO parametro(nombre, valor) VALUES('facturacion','FALSE');
INSERT INTO parametro(nombre, valor) VALUES('email','info@icreativa.com.ec');
INSERT INTO parametro(nombre, valor) VALUES('impresora','0');
INSERT INTO parametro(nombre, valor) VALUES('contador','1');
INSERT INTO parametro(nombre, valor) VALUES('empleado','0');
INSERT INTO parametro(nombre, valor) VALUES('val_stock','FALSE');
INSERT INTO parametro(nombre, valor) VALUES('recibos','FALSE');
INSERT INTO parametro(nombre, valor) VALUES('catalogo','TRUE');
 